import Head from "next/head";
import { Button, Flex, Modal, ModalBody, ModalCloseButton, ModalContent, ModalFooter, ModalHeader, ModalOverlay, Text, useDisclosure } from "@chakra-ui/react";
import Menu from "@/components/Menu";
import dynamic from "next/dynamic";
import Card from "@/components/Card";
import ProgressBar from "@/components/ProgressBar";
import { useStyles } from "@/context/StylesContext";
import CircleChartGroup from "@/components/CircleChartGroup";
import Filter from "@/components/Filter";
import { useDb } from "@/hook/useDb";
import { CircleProgressBar } from "@/components/CircleProgressBar";
import { useEffect } from "react";
import useSound from 'use-sound';

const Map = dynamic(() => import("@/components/Map"), { ssr: false });

const data = [
  {
    label: "Grande Goiania",
    value: 70,
    color: "#dc8215",
  },
  {
    label: "Entorno do Distrito Federal",
    value: 47,
    color: "#dc8215",
  },
  {
    label: "Sudeste Goiano",
    value: 25,
    color: "#e52305",
  },
  {
    label: "Sul Goiano",
    value: 3,
    color: "#056ae5",
  },
  
];


export default function Home() {
  const { theme } = useStyles();
  const { schoolList } = useDb();
  const { isOpen, onOpen, onClose } = useDisclosure()

  useEffect(()=>{
    if (onOpen) {
      setTimeout(()=>{
        onOpen()
      },3000)
    }
  }, [])



  function closeModal (){
    onClose()
  }

  return (

    <>
      <Head>
        <title>Escola Segura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./avatar.svg" />
      </Head>
      
      <Modal onClose={closeModal} size={"xl"} isOpen={isOpen}>
        <ModalOverlay />
        <ModalContent backgroundColor="#ab2e47">
          <ModalHeader color="white">Alerta de Emergência!</ModalHeader>
          <ModalCloseButton />
          <ModalBody display="flex" flexDir="column" gap="24px">
            <Text color="white" fontSize="24px" fontWeight={600}>
               Possivel atentado
            </Text>
<Flex gap="16px">
<Text color="white" fontSize="18px" fontWeight={500}>
              Localização:
            </Text>
            <Flex flexDir="column">
            <Text color="white" fontSize="18px" fontWeight={500}>
              Escola Estadual Imperatriz Leopodina
            </Text>
            <Text color="white"fontSize="14px"  fontWeight={400}>
              Rua das Rosas 242 - Goiania
            </Text>
</Flex>
            
            </Flex>
          </ModalBody>
          <ModalFooter>
            <Button onClick={onClose}>Close</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>

      <Flex>
        <Menu />

        <Flex
          padding="24px"
          pl="309px"
          background={theme.background}
          w="100%"
          justifyContent="flex-start"
          alignItems="flex-start"
          flexWrap="wrap"
          gap="16px"
          minH="100vh"
        >
          <Filter schools={schoolList.map(item => item.name)} selected={schoolList.map(item => item.name)} />

          <Card
            title="Incidência de violência entre alunos"
            footer="Baseado no número de alertas registrados pelas escolas usuárias do Escola Segura da região. É de extrema importância a mobilização de material de conscientização."
          >
            <CircleChartGroup data={data} />
          </Card>

          <Card title="Scanner de palavras na DarkWeb" left={true}>
            <Flex gap="8px" flexDir="column">
              {schoolList.slice(0, 5).map((item) => {
                return (
                  <ProgressBar
                    key={item.id}
                    label={item.name}
                    percent={item.metrics.darkWeb.amount * 10}
                  />
                );
              })}
            </Flex>
          </Card>

          <Flex w="100%" minHeight="550px">
            <Flex w="100%" height="550px">

            <Map />
            </Flex>

            <Card
              title="Escolas Monitoras pelo Programa Escola Segura"
              footer="Baseado no número de alertas registrados pelas escolas usuárias do Escola Segura da região. É de extrema importância a mobilização de material de conscientização."
            >
              <CircleProgressBar progress={67} color="#2191aa" />
            </Card>
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}
