import { Flex, Heading } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';
import { useStyles } from '@/context/StylesContext';
import Menu from '@/components/Menu';
import SchoolCard from '@/components/SchoolCard';

// import { Container } from './styles';

const escolas: React.FC = () => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const { theme } = useStyles()


  return <>
   <Head>
        <title>Escola Segura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./avatar.svg" />
      </Head>

      <Flex>
        <Menu />

        <Flex padding="24px" pl="309px" background={theme.background} w="100%" justifyContent="flex-start" alignItems="flex-start" flexWrap="wrap" gap="16px" >
            <Heading>Escolas próximas a ganharem o selo</Heading>

            <Flex flexWrap="wrap" gap="16px">
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
                <SchoolCard name='Ensino em Período Integral Iris Rezende Machado' />
            </Flex>
        </Flex>

      </Flex>
      </>;
}

export default escolas;