/* eslint-disable react-hooks/rules-of-hooks */
import { Button, Flex, Heading } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';
import { useStyles } from '@/context/StylesContext';
import Menu from '@/components/Menu';
import SchoolCard from '@/components/SchoolCard';
import { useRouter } from 'next/router';

import { AddIcon } from '@chakra-ui/icons'
import { useDb } from '@/hook/useDb';

// import { Container } from './styles';

const Escolas: React.FC = () => {
    const { theme } = useStyles();
    const { push } = useRouter();
    const { schoolList } = useDb()

  return <>
   <Head>
        <title>Escola Segura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./avatar.svg" />
      </Head>

      <Flex>
        <Menu />

        <Flex padding="24px" pl="309px" minH="100vh" background={theme.background} w="100%" justifyContent="flex-start" alignItems="flex-start" flexWrap="wrap" gap="16px" >
            <Flex justifyContent="space-between"mb="56px" flexWrap="wrap" gap='16px' width="100%">
                <Heading color={theme.text.primary}>Escolas próximas a ganharem o selo</Heading>
                <Button rightIcon={<AddIcon />} background={theme.menu.background} color={theme.text.primary} >
                    Adicionar escola
                </Button>
                
            </Flex>

            <Flex flexWrap="wrap" gap="16px">
{schoolList.map(school => 
    
    <SchoolCard key={school.id} name={school.name} progress={school.progress} onClick={() => push(`/escolas/${school.id}`)} />
    )}
                
            </Flex>
        </Flex>

      </Flex>
      </>;
}

export default Escolas;